hello-world-2020/hello_world_nlanson.cpp

Hi, 
Thanks for letting me add in my code.

hello_world_nlanson.cpp

---

hello-world-2020/hello_world.c
hello-world-2020/hello_world_prabor.c

c hello world

---

hello-world-2020/hello_world_abhishekdas.go

Please review my PR for Hacktoberfest.

Hello World in Golang

---

hello-world-2020/hello_world_Kuldeep-Kumar-Sharma.php

hackoberfest php hello world

---

hello-world-2020/hello_world_hemanth987.html

Update by Hemanth987

---

hello-world-2020/hello_world_ruansena.js

hello world js -ruansenadev

---

hello-world-2020/hello_world_vinaysagarsharma.js

I've made my first PR in this repo by adding the Hello World script in ReactJS.

added Hello World script in ReactJS

---

hello-world-2020/hello_world_ChristopherHauschild.py

I added hello world in Django language

feat: add Django hello world

---

hello-world-2020/hello_world_nartuom.html

Add Nartuom's hello world script :)

---

hello-world-2020/hello_world_hemanth987.html
hello-world-2020/hello_world_nartuom.html

ADDED COLOR EFFECT AND IMPROVED DOCS.

---

hello-world-2020/hello_world_jeanllopes.js

Add file hello_world_jeanllopes.js

Add file hello_world_jeanllopes.js

---

hello-world-2020/hello_world_yusril.html

Created hello-world-yusril.html

Hello world yusril

---

hello_world.py

Reverts AselSiriwardena/hacktoberfest-beginner#45

Revert "Create hello_world.py"

---

hello-world-2020/hello_world_rr_2404.java

added a java file

---

hello-world-2021/hello_world_pman47.c

Printing Hello World using c language.

Created hello_world_pman47.c

---

hello-world-2021/hello_world_husinassegaff.c
hello-world-2021/hello_world_husinassegaff.cpp
hello-world-2021/hello_world_husinassegaff.java
hello-world-2021/hello_world_husinassegaff.js

Hello, I have added Hello World program in C, C++, Java, and Javascript
Thanks

Add Hello World in Several Programming Languages

---

hello-world-2021/hello_world_pasindu.pas

Wrote a whole new hello world script in pascal

Added pascal language

---

hello-world-2021/hello_world_animated/hello_world.css
hello-world-2021/hello_world_animated/hello_world.html

added Animated Hello-World using HTML and CSS

added hello_world_animated 

---

hello-world-2021/hello_world_chamaru.py

Hello World from Chamaru

---

hello-world-2021/hello_world_Rafid009.ex

Please accept and add the `hacktoberfest-accepted` label.
Thank you.

Hello World In Elixir

---

hello-world-2021/Helloworld_abhishek.cpp

Created a hello world program in C++

Helloworld_abhishek.cpp

---

hello-world-2021/hellow_world_yani.ipynb

hi, i create jupyter hellow world for hacktoberfest

jupyter hellow world

---

hello-wold-2022/hello_world_carltonstith.js

2022 folder and js file added for Hacktoberfest 2022

2022 folder and js file added

---

git checkout -hacktoberfest 2022

Please accept my pull request and make it valid for hacktoberfest 2022

Create git checkout -hacktoberfest 2022

---

hello-wold-2022/Hellow_world22

Hi , I have also contributed the same
:)
Thanks

commit message
